# Generated by Django 5.2 on 2025-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion_emoji_name", models.CharField(max_length=20)),
                (
                    "emotion_emoji_path",
                    models.CharField(
                        blank=True,
                        help_text="The path to emotion in object storage.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "current_emoji_url",
                    models.CharField(
                        blank=True,
                        help_text="Current presigned url for the emoji.",
                        max_length=2046,
                        null=True,
                    ),
                ),
                (
                    "emoji_url_expiry_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration time of the current url.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
