# Generated by Django 5.2 on 2025-05-27 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="currentemotion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currentemotion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="currentemotion",
            name="current_emoji_url",
            field=models.URLField(
                blank=True,
                help_text="Current presigned url for the emoji.",
                max_length=2046,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="currentemotion",
            name="emotion_emoji_path",
            field=models.CharField(
                blank=True,
                help_text="The path to emotion emoji in object storage.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hashtag_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
                (
                    "post_image_path",
                    models.CharField(
                        blank=True,
                        help_text="The path to post image in object storage.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "current_post_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Current presigned url for the post image.",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "post_image_url_expiry_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration time of the current url.",
                        null=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("friends_only", "Friends Only"),
                        ],
                        default="friends_only",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_post",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="The actual comment on a post.", max_length=1000
                    ),
                ),
                ("commented_at", models.DateTimeField(auto_now_add=True)),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of likes on this comment."
                    ),
                ),
                (
                    "commented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_on_post",
                        to="core.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostHashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hashtag"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="type_of_post",
            field=models.ManyToManyField(
                related_name="tagged_posts",
                through="core.PostHashTag",
                to="core.hashtag",
            ),
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_liked",
                        to="core.comment",
                    ),
                ),
                (
                    "liked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comment"], name="core_commen_comment_650937_idx"
                    ),
                    models.Index(
                        fields=["liked_by"], name="core_commen_liked_b_ceee36_idx"
                    ),
                ],
                "unique_together": {("liked_by", "comment")},
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "liked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_on_post",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["post"], name="core_like_post_id_777ee2_idx"),
                    models.Index(
                        fields=["liked_by"], name="core_like_liked_b_708d4a_idx"
                    ),
                ],
                "unique_together": {("liked_by", "post")},
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["commented_at"], name="core_commen_comment_e02a12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["like_count"], name="core_commen_like_co_8e8a98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(
                fields=["hashtag"], name="core_postha_hashtag_2e5e8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(fields=["post"], name="core_postha_post_id_9e2b29_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="posthashtag",
            unique_together={("post", "hashtag")},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="core_post_created_2da706_idx"
            ),
        ),
    ]
