# Generated by Django 5.2 on 2025-06-18 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_currentemotion_created_at_currentemotion_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="core_commen_comment_e02a12_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="core_commen_like_co_8e8a98_idx",
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_on_comment",
                to="core.comment",
            ),
        ),
        migrations.AlterField(
            model_name="currentemotion",
            name="current_emoji_url",
            field=models.URLField(
                blank=True,
                help_text="Current presigned url for the emoji.",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.CharField(
                help_text="Text caption describing the post.", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Flag to indicate if the post is soft deleted."
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("friends_only", "Friends Only"),
                ],
                default="friends_only",
                help_text="Visibility level of the post (Public, Private, or Friends Only).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="posthashtag",
            name="hashtag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.hashtag",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "commented_at"], name="core_commen_post_id_d15e27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "like_count"], name="core_commen_post_id_d5df9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "like_count", "id"],
                name="core_commen_post_id_39924e_idx",
            ),
        ),
    ]
