# Generated by Django 5.2 on 2025-06-19 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_comment_core_commen_comment_e02a12_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="commentlike",
            options={
                "verbose_name": "CommentLike",
                "verbose_name_plural": "CommentLikes",
            },
        ),
        migrations.AlterModelOptions(
            name="currentemotion",
            options={
                "verbose_name": "CurrentEmotion",
                "verbose_name_plural": "CurrentEmotions",
            },
        ),
        migrations.AlterModelOptions(
            name="hashtag",
            options={"verbose_name": "Hashtag", "verbose_name_plural": "Hashtags"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Like", "verbose_name_plural": "Likes"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="posthashtag",
            options={
                "verbose_name": "PostHashTag",
                "verbose_name_plural": "PostHashTags",
            },
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="core_commen_post_id_d5df9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="core_commen_post_id_39924e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="posthashtag",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="comment",
            name="like_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="current_post_image_url",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_image_path",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_image_url_expiry_time",
        ),
        migrations.AddField(
            model_name="post",
            name="is_video",
            field=models.BooleanField(
                default=False, help_text="Flag to indicate if media is a video."
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="media_public_id",
            field=models.CharField(
                blank=True,
                help_text="Cloudinary public ID for the uploaded image/video.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.CharField(
                help_text="Text caption describing the post.", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="posthashtag",
            name="hashtag",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hashtag",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("liked_by", "comment"), name="unique_liked_by_comment"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("liked_by", "post"), name="unique_liked_by_post"
            ),
        ),
        migrations.AddConstraint(
            model_name="posthashtag",
            constraint=models.UniqueConstraint(
                fields=("post", "hashtag"), name="unique_post_hashtag"
            ),
        ),
    ]
