# Generated by Django 5.2 on 2025-06-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_comment_options_alter_commentlike_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_video",
        ),
        migrations.RemoveField(
            model_name="post",
            name="media_public_id",
        ),
        migrations.CreateModel(
            name="MediaUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_public_id",
                    models.CharField(
                        blank=True,
                        help_text="Cloudinary public ID for the uploaded image/video.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_video",
                    models.BooleanField(
                        default=False, help_text="Flag to indicate if media is a video."
                    ),
                ),
                ("upload_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_media",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["upload_order"],
            },
        ),
    ]
