# Generated by Django 5.2 on 2025-06-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_post_is_video_remove_post_media_public_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediaupload",
            options={
                "ordering": ["upload_order"],
                "verbose_name": "Media Upload",
                "verbose_name_plural": "Media Uploads",
            },
        ),
        migrations.RenameField(
            model_name="mediaupload",
            old_name="media_public_id",
            new_name="public_id",
        ),
    ]
