# Generated by Django 5.2 on 2025-06-23 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_friend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("deleted", "Deleted by sender"),
                        ],
                        default="pending",
                        help_text="The current status of the friend request.",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when the friend request was created.",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when the friend request was accepted.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friend Request",
                "verbose_name_plural": "Friend Requests",
            },
        ),
        migrations.AddField(
            model_name="friend",
            name="accepted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="friend",
            name="user1",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_user_in_the_friendship",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="user2",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_user_in_the_friendship",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_friendship"
            ),
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.CheckConstraint(
                condition=models.Q(("user1", models.F("user2")), _negated=True),
                name="no_self_friendship",
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="from_user",
            field=models.ForeignKey(
                help_text="The user who sent the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="to_user",
            field=models.ForeignKey(
                help_text="The user who received the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_friend_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_user", models.F("to_user")), _negated=True),
                name="no_self_request",
            ),
        ),
    ]
