# Generated by Django 5.2 on 2025-07-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_friendrequest_friend_accepted_at_friend_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrentEmotion",
            new_name="Emotion",
        ),
    ]
