# Generated by Django 5.2 on 2025-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_currentemotion_emotion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emotion",
            options={
                "ordering": ["-upload_order"],
                "verbose_name": "CurrentEmotion",
                "verbose_name_plural": "CurrentEmotions",
            },
        ),
        migrations.RemoveField(
            model_name="emotion",
            name="current_emoji_url",
        ),
        migrations.RemoveField(
            model_name="emotion",
            name="emoji_url_expiry_time",
        ),
        migrations.RemoveField(
            model_name="emotion",
            name="emotion_emoji_path",
        ),
        migrations.AddField(
            model_name="emotion",
            name="emotion_public_id",
            field=models.CharField(
                default=1234567890, help_text="Public id of the emoji"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emotion",
            name="upload_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emotion",
            name="emotion_emoji_name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
