# Generated by Django 5.2 on 2025-07-16 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_emotion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emotion",
            options={
                "ordering": ["-upload_order"],
                "verbose_name": "Emotion",
                "verbose_name_plural": "Emotions",
            },
        ),
        migrations.CreateModel(
            name="UserEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_emotions",
                        to="core.emotion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Emotion",
                "verbose_name_plural": "User Emotions",
                "ordering": ["-noted_at"],
            },
        ),
    ]
