# Generated by Django 5.2 on 2025-07-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_emotion_options_useremotion"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendrequest",
            name="unique_friend_request",
        ),
    ]
