# Generated by Django 5.2 on 2025-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=15),
            preserve_default=False,
        ),
    ]
