# Generated by Django 5.2 on 2025-05-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_areaofinterest_userareaofinterest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userareaofinterest",
            old_name="usersInterest",
            new_name="users_interest",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "SUPERUSER"),
                    ("admin", "ADMIN"),
                    ("user", "USER"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userareaofinterest",
            unique_together={("user", "users_interest")},
        ),
    ]
