# Generated by Django 5.2 on 2025-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="synced_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="synced_phone_number",
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="synced_username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
