# Generated by Django 5.2 on 2025-06-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_synced_email_profile_synced_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="uploaded_at",
            new_name="created_at",
        ),
    ]
