# Generated by Django 5.2 on 2025-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_uploaded_at_profile_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
