# Generated by Django 5.2 on 2025-06-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="synced_phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
