# Generated by Django 5.2 on 2025-10-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationparticipant",
            options={
                "verbose_name": "Conversation Participant",
                "verbose_name_plural": "Conversation Participants",
            },
        ),
    ]
