# Generated by Django 5.2 on 2025-07-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
