# Generated by Django 5.2 on 2025-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="idcard_public_id",
            field=models.CharField(
                blank=True,
                help_text="Public id of the id card.",
                max_length=2056,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="selfie_public_id",
            field=models.CharField(
                blank=True,
                help_text="Public id of the selfie.",
                max_length=2056,
                null=True,
            ),
        ),
    ]
