# Generated by Django 5.2 on 2026-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_idcard_public_id_user_selfie_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='has_completed_interests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='areaofinterest',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_interest_name'),
        ),
    ]
