# Generated by Django 5.2 on 2026-03-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_areaofinterest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterest',
            options={'ordering': ['created_at']},
        ),
    ]
