# Generated by Django 5.2 on 2025-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emotion",
            name="emotion_public_id",
            field=models.CharField(help_text="Public id of the emoji", max_length=2056),
        ),
    ]
