# Generated by Django 5.2 on 2025-10-15 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentlike",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="commentlike",
            name="liked_by",
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_friend_request"
            ),
        ),
        migrations.DeleteModel(
            name="CommentLike",
        ),
    ]
