# Generated by Django 5.2 on 2026-03-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emotion_emotion_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, help_text='Text caption describing the post.', max_length=512, null=True),
        ),
    ]
