# Generated by Django 5.2 on 2026-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderation_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_review', 'Pending Review'), ('blocked', 'Blocked')], default='approved', max_length=20),
        ),
    ]
