# Generated by Django 5.2 on 2026-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('friend_request', 'Friend Request'), ('message', 'Message'), ('post_moderation', 'Post Moderation')], max_length=30),
        ),
    ]
